### ISSUE TITLE
Use a defined color for <code> background

### ISSUE THREAD

**Issue by alienlebarge** [vdch/regenair-fabricator#132]
## Description

Color background of `code` elements is not using a defined color in the color palette.

``` css
:root {
    --code-text-background: color(var(--base-text-color) a(5%));
}
```
## Ask

Define a light gray to use for that kind of purpose
## To Do
- [x] Define more grays 
- [x] Use it in the CSS
