### ISSUE TITLE
Beautify CSS output

### ISSUE THREAD

**Issue by alienlebarge** [vdch/regenair-fabricator#137]
## Description

There some _not nice_ things in the outputed CSS

``` css
...
        &:checked + label::before {
            background-color: var(--form-color-checked);
            background-size: var(--form-checkbox-background-image-size);

            box-shadow: 0
                        0
                        0
                        var(--form-border-width)
                        var(--form-color-checked);
        }
...
```

This is written like that to avoid the having line length over 80 chars

``` css
...
.vd-form input[type="checkbox"]:checked + label::before, .vd-form input[type="radio"]:checked + label::before {
    background-color: #3e9ff0;
    background-color: rgba(62, 159, 240, 1);
    background-size: 0.79365rem;
    box-shadow: 0 0 0 1px rgba(62, 159, 240, 1);
    box-shadow: 0
                        0
                        0
                        1px
                        rgba(62, 159, 240, 1);
}
...
```
## Ask

Clean the CSS output
## To Do
- [x] Use a plugin
## Additional Info

Have a look at https://github.com/ben-eb/perfectionist
