### ISSUE TITLE
Refactor .button--disabled style

### ISSUE THREAD

**Issue by alienlebarge** [vdch/regenair-fabricator#183]
## Description

The current generated CSS have 3 time the same style rules instead of having one style rule with all selector list.
## Ask

Transform that

``` css
/* Button disabled */

.vd-button--disabled {
    color: inherit;
    background-color: #aeb0b5;
    background-color: rgba(174, 176, 181, 1);
}

.vd-button--disabled:hover, .vd-button--disabled.is-hover {
    color: inherit;
    background-color: #aeb0b5;
    background-color: rgba(174, 176, 181, 1);
}

.vd-button--disabled:active, .vd-button--disabled.is-active {
    color: inherit;
    background-color: #aeb0b5;
    background-color: rgba(174, 176, 181, 1);
}
```

to this

``` css
/* Button disabled */

.vd-button--disabled, .vd-button--disabled:hover, .vd-button--disabled.is-hover, .vd-button--disabled:active, .vd-button--disabled.is-active {
    color: inherit;
    background-color: #aeb0b5;
    background-color: rgba(174, 176, 181, 1);
}
```
## To Do
- [x] Eveluate the need of a _mixin_
- [x] Rewrite the CSS
