### ISSUE TITLE
Fix images size in IE

### ISSUE THREAD

**Issue by alienlebarge** [vdch/regenair-fabricator#530]
## Description
The image is too big in IE and is not centered

## Ask
Let's fix that to make the image looks the same in IE as in Chrome.

## To Do

Adding a `max-width` **could** fix it
```css
@media (min-width: 768px)
.vd-teaser-img {
    margin-left: 25%;
    margin-right: 25%;
    max-width: 50%; /* <--- */
}
```

## Additional Info
related to refactor of `.vd-teaser-image` in #526
