### ISSUE TITLE
Figures breaks grid

### ISSUE THREAD

**Issue by alienlebarge** [vdch/regenair-fabricator#604]
## Description

When using [Figures](http://v4-alpha.getbootstrap.com/content/figures/) in a grid, it doesn't fit the width of the container.

This due to bootstrap 
```css
.figure {
  // Ensures the caption's text aligns with the image.
  display: inline-block;
}
```

see twbs/bootstrap#21886 for more info

## Additional Info
- twbs/bootstrap#21886

![napkin 4 01 02 17 a 8 03 54 am](https://cloud.githubusercontent.com/assets/611234/22497875/d7aca3bc-e854-11e6-9418-8ff52d847b84.png)
